---
apiVersion: v1
kind: Service
metadata:
  name: manager-metrics
  labels:
    app: floorist-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - port: 9000
    targetPort: 8080
    protocol: TCP
    name: metrics
