resources:
- ./local

images:
- name: quay.io/redhat-services-prod/insights-management-tenant/insights-floorist/floorist-operator
  newName: ${IMAGE}
  newTag: ${IMAGE_TAG}

patches:
- path: test_params.config.yaml
  target:
    group: batch
    kind: Job
    name: stage-test
    version: v1

- path: test_service_account_params.config.yaml
  target:
    version: v1
    kind: ServiceAccount
    name: stage-test-service-account

- path: clusterrole_patch.yaml

- path: clusterrolebinding_patch.yaml
