# permissions for end users to view floorplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floorplan-viewer-role
rules:
- apiGroups:
  - metrics.console.redhat.com
  resources:
  - floorplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.console.redhat.com
  resources:
  - floorplans/status
  verbs:
  - get
