{
 "title": "Floorist",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success of last runs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_job_status_completion_time{job_name=~\"floorist-.+-exporter-.+\"}) by (namespace) > bool time() - 86400) / count(count(kube_job_status_completion_time{job_name=~\"floorist-.+-exporter-.+\"}) by (namespace))"
    }
   ]
  },
  {
   "title": "Number of last run failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_job_status_completion_time{job_name=~\"floorist-.+-exporter-.+\"}) by (namespace) <= bool time() - 86400)"
    }
   ]
  },
  {
   "title": "Apps Onboarded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_info{cronjob=~\"^floorist-.+-exporter$\"})"
    }
   ]
  },
  {
   "title": "FloorPlan reconciles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ansible_operator_reconciles_count{GVK=\"metrics.console.redhat.com/v1alpha1, Kind=FloorPlan\", namespace=\"floorist-operator-system\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Operator SDK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ansible_operator_build_info{namespace=\"floorist-operator-system\"}"
    }
   ]
  },
  { "title": "Tracking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Floorist Export Jobs",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(label_replace(kube_job_status_completion_time{job_name=~\"floorist-.+-exporter-.+\"},\"app\", \"$1\",\"job_name\",\"floorist-(.+)-exporter-.+\")) by (app) > bool time() - 86400",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Max Memory Usage by namespace",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(label_replace(max_over_time(container_memory_working_set_bytes{pod=~\"floorist-.+-exporter-.+\"}[24h]), \"app\", \"$1\",\"pod\",\"floorist-(.+)-exporter-.+\")) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Job duration by namespace",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(label_replace(max_over_time(kube_job_status_completion_time{job_name=~\"floorist-.+-exporter-.+\"}[24h]), \"app\", \"$1\",\"job_name\",\"floorist-(.+)-exporter-.+\")) by (app) - max(label_replace(max_over_time(kube_job_status_start_time{job_name=~\"floorist-.+-exporter-.+\"}[24h]), \"app\", \"$1\",\"job_name\",\"floorist-(.+)-exporter-.+\")) by (app)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Operator CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(pod:container_cpu_usage:sum{namespace=\"floorist-operator-system\"}) by (pod) / avg(kube_pod_container_resource_limits{namespace=\"floorist-operator-system\",resource=\"cpu\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator Max Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(sum(container_memory_usage_bytes{namespace=\"floorist-operator-system\"}) by (pod)) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}