apiVersion: batch/v1
kind: Job
metadata:
  name: stage-test
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: stage-test-service-account
      containers:
        - image: controller:latest
          name: floorist-operator-stage-test
          imagePullPolicy: Always
          command:
            - sh
          args:
            - stage_test.sh
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
