apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stage-test-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
