apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stage-test-rolebinding
roleRef:
  kind: Role
  name: stage-test-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: stage-test-service-account
