apiVersion: metrics.console.redhat.com/v1alpha1
kind: FloorPlan
metadata:
  name: floorplan-sample
spec:
  queries:
  - prefix: dumps/people
    query: >-
      SELECT name, email, birthyear FROM people;
  - prefix: dumps/cities
    query: >-
      SELECT name AS city_name, zip, country FROM cities;
    chunksize: 100
  database:
    secretName: postgresql-credentials
  objectStore:
    secretName: minio-access
