# Apply via patch as jsonpatch using:
# kubectl patch secret env-default-minio --type=json --patch-file config/clowder/minio/minio_secret_consitency.yaml
---
- op: add
  path: /data/bucket
  value: bXlidWNrZXQ=
- op: add
  path: /data/aws_region
  value: bG9jYWw=
- op: add
  path: /data/endpoint
  value: aHR0cDovL2Vudi1kZWZhdWx0LW1pbmlvLmRlZmF1bHQuc3ZjOjkwMDA=
- op: copy
  from: /data/accessKey
  path: /data/aws_access_key_id
- op: copy
  from: /data/secretKey
  path: /data/aws_secret_access_key
