
namespace: floorist-operator-system

namePrefix: floorist-operator-

resources:
- ../crd
- ../rbac
- ../manager

patches:
- path: manager_params.config.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager

- path: service_account_params.config.yaml
  target:
    version: v1
    kind: ServiceAccount
    name: controller-manager
