- op: replace
  path: /spec/template/spec/containers/0/image
  value: ${IMAGE}:${IMAGE_TAG}
- op: replace
  path: /spec/template/spec/containers/0/env/1/value
  value: "${FLOORIST_IMAGE}"
- op: replace
  path: /spec/template/spec/containers/0/env/2/value
  value: "${FLOORIST_IMAGE_TAG}"
