- op: replace
  path: /spec/template/spec/containers/0/image
  value: ${IMAGE}:${IMAGE_TAG}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --ansible-args='--extra-vars "floorist_image_tag=${FLOORIST_IMAGE_TAG}"'
