- description: Operator image
  name: IMAGE
  value: quay.io/cloudservices/floorist-operator
- description: Operator image tag
  name: IMAGE_TAG
  value: latest
- description: Floorist exporter tool image
  name: FLOORIST_IMAGE
  value: quay.io/cloudservices/floorist
- description: Floorist exporter tool image tag
  name: FLOORIST_IMAGE_TAG
  value: a5d1b1b
