---
apiVersion: cloud.redhat.com/v1alpha1
# Custom Resource defined as part of the Clowder API
kind: ClowdEnvironment
metadata:
  name: env-default
spec:
  targetNamespace: default

  # Providers all your app to consume configuration
  # data automatically based on your request
  providers:

    # provides a k8s service on port 8000
    web:
      port: 8000
      privatePort: 8080
      mode: operator

    # provides a prometheus metrics port on 9000
    metrics:
      port: 9000
      mode: operator
      path: "/metrics"

    kafka:
      mode: none

    # Clowder supports postgres 10 and 12. Specify the name
    # and other details in the clowdapp
    db:
      mode: local

    logging:
      mode: none

    # Deploys a local minio pod for object storage
    objectStore:
      mode: minio

    inMemoryDb:
      mode: none

  resourceDefaults:
    limits:
      cpu: "500m"
      memory: "8192Mi"
    requests:
      cpu: "300m"
      memory: "1024Mi"

