name: Regular base image update check
on:
  schedule:
    - cron: "5 11 * * *"
  workflow_dispatch:

jobs:
  latest-floorist:
    name: Check latest Floorist image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install skopeo, jq, and kustomize
        run: sudo apt-get install -y skopeo jq
      - name: Get and set latest Floorist image
        run: |
          tag=$(curl -s -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/RedHatInsights/floorist/branches/master \
            | jq -r '.commit.sha' \
            | cut -c1-7)
          [[ "$tag" != "null" && "$tag" != "" ]]
          skopeo inspect "docker://quay.io/redhat-services-prod/insights-management-tenant/insights-floorist/floorist:$tag" > /dev/null
          sed -i "/name: FLOORIST_IMAGE_TAG/{n;s/value: .*/value: '$tag'/}" \
            config/templated/template_params.yaml
          make openshift-templates
      - name: Commit changes (if any)
        run: |
          git config user.name 'Update-a-Bot'
          git config user.email 'insights@redhat.com'
          git add -A
          git commit -m "chore: update floorist image tag" || echo "No new changes"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'chore: update floorist image tag to latest'
          branch: automation/floorist-latest
